name: build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ylarod/ddk:android16-6.12
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build lkmloader
        run: make -C lkmloader
      - name: Build cksu
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: cksu-android16-6.12
          path: |
            cksu.ko
            lkmloader/lkmloader.ko
